[package]
name = "safe-nodejs"
version = "0.11.0"
authors = ["Josh Wilson <joshuef@gmail.com>", "Gabriel Viganotti <gabrielviganotti@gmail.com>"]
license = "MIT OR BSD-3-Clause"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
name = "safe_nodejs"
crate-type = ["cdylib"]

[build-dependencies]
#neon-build = "~0.3.2"
neon-build = { git = "https://github.com/geovie/neon", branch = "feature/threadsafe_callback" }

[dependencies]
log = "~0.4.8"
env_logger = "~0.7.1"
safe-api = { version = "~0.11.0", features = ["app", "authd_client"] }
#neon = "~0.3.2"
neon = { git = "https://github.com/geovie/neon", branch = "feature/threadsafe_callback" }
#neon-serde = "~0.3.0"
neon-serde = { git = "https://github.com/bochaco/neon-serde", branch = "neon-threadsafe_callback" }
async-std = "1.5.0"

[patch.crates-io]
neon-runtime = { git = "https://github.com/geovie/neon", branch = "feature/threadsafe_callback" }

[features]
mock-network = ["safe-api/mock-network"]
fake-auth = ["safe-api/fake-auth"]
scl-mock = ["safe-api/scl-mock"]
