name: Build on tag

on:
  create:
    tags:
      - v*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ELECTRON_LATEST: "8.4.0"
  ELECTRON_ONE_BACK: "7.3.2"
  NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  builds:
    name: Build on tag
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["10", "12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # electron: ["7.3.2", "8.4.0"]
    steps:
      - name: Linux install jq
        run: sudo apt-get install jq
        if: matrix.os == 'ubuntu-latest'

      - name: Mac install jq
        run: brew install jq
        if: matrix.os == 'macos-latest'

      - name: Windows install jq
        run: choco install jq
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Yarn Install
        run: |
          yarn
          yarn global add neon-cli
      - name: set package version as env
        run: echo "PACKAGE_VERSION=$(jq .version ./package.json)" >> $GITHUB_ENV

      - name: Build for node ${{ matrix.node }}
        run: |
          yarn package
          yarn publish-gh-draft

      - name: Archive Node Build
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}-${{ matrix.node }}
          path: ./build/Release/index.node

      - name: Remove build
        if: matrix.os == 'windows-latest'
        run: npx trash-cli build || true

      - name: Remove build
        if: matrix.os != 'windows-latest'
        run: rm -rf build || true

      - name: Build Electron Latest
        if: matrix.node == '12'
        run: yarn cross-env npm_config_target=${{ env.ELECTRON_LATEST }} npm_config_arch=x64 npm_config_disturl=https://electronjs.org/headers npm_config_runtime=electron neon build --release

      - name: Remove target
        if: matrix.os == 'windows-latest'
        run: npx trash-cli native/target

      - name: Remove target
        if: matrix.os != 'windows-latest'
        run: rm -rf native/target || true

      - name: Package Electron Latest
        if: matrix.node == '12'
        run: |
            yarn node-pre-gyp package --runtime=electron --target=${{ env.ELECTRON_LATEST }} --dist-url=https://electronjs.org/headers
            yarn publish-gh-draft || exit 0

      - name: Remove build
        if: matrix.os == 'windows-latest'
        run: npx trash-cli build || true

      - name: Remove build
        if: matrix.os != 'windows-latest'
        run: rm -rf build || true

      - name: Build Electron Latest -1
        if: matrix.node == '12'
        run: yarn cross-env npm_config_target=${{ env.ELECTRON_ONE_BACK }} npm_config_arch=x64 npm_config_disturl=https://electronjs.org/headers npm_config_runtime=electron neon build --release

      - name: Remove target
        if: matrix.os == 'windows-latest'
        run: npx trash-cli native/target

      - name: Remove target
        if: matrix.os != 'windows-latest'
        run: rm -rf native/target || true

      - name: Package Electron Latest -1
        if: matrix.node == '12'
        run: |
            yarn node-pre-gyp package --runtime=electron --target=${{ env.ELECTRON_ONE_BACK }} --dist-url=https://electronjs.org/headers
            yarn publish-gh-draft || exit 0

  publish:
    name: Publish Release
    needs: builds
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      - name: Set tag as env
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      - name: lets check tag
        shell: bash
        run: echo ${{ env.RELEASE_VERSION }}

      - name: Generate Changelog
        shell: bash
        run: echo "RELEASE_COPY=$(awk '/# \[/{c++;p=1}{if(c==2){exit}}p;' CHANGELOG.md )" >> $GITHUB_ENV

      - name: Release generation
        uses: Xotl/cool-github-releases@ef50014218e6139d534f725f69aabe3728ea9b2e
        with:
          mode: update
          body_mrkdwn: ${{ env.RELEASE_COPY }}
          isPrerelease: false
          github_token: ${{ github.token }}
          tag_name: ${{ env.RELEASE_VERSION }}
